dist: focal
language: php

php:
    - 7.4

install:
    - composer install

script:
    - vendor/bin/phpcs --standard=psr2 src/
    - vendor/bin/phpstan analyse
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
